### ISSUE TITLE
How to test the pretrained modal on my own video?

### ISSUE THREAD

**Issue by G1tQuality** [ayshrv/gmrw#4]

**Comment by G1tQuality** [comment]
I want to infer on my videos (only several sequences) and visualize them. Should I follow test_tapvid?

**Comment by ayshrv** [comment]
Yes, instead of using the loaded data, you can provide your video to [run_crw()](https://github.com/ayshrv/gmrw/blob/bf832bda941ecf54334c2b0677ef3b77a714b485/test_on_tapvid.py#L132) and use the visualization from [here](https://github.com/ayshrv/gmrw/blob/bf832bda941ecf54334c2b0677ef3b77a714b485/train_kubric.py#L56).
